apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - image: khanster/frontend:kube
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always