apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb-auth:3306/users
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: khanster/auth:kube
          name: auth
          ports:
            - containerPort: 8040
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/app
              name: auth-cm0
            - mountPath: /root/.m2
              name: auth-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: auth-cm0
          name: auth-cm0
        - name: auth-claim1
          persistentVolumeClaim:
            claimName: auth-claim1
