apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  type: LoadBalancer
  clusterIP:  10.96.0.11
  externalIP: 10.96.0.11
  ports:
    - name: "8040"
      port: 8040
      targetPort: 8040
  selector:
    io.kompose.service: auth
