apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - image: khanster/frontend:kube
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
        - image: khanster/auth:kube
          name: auth
          ports:
            - containerPort: 8040
              protocol: TCP
        - image: khanster/auth-client:kube
          name: auth-client
          ports:
            - containerPort: 8090
              protocol: TCP
        - image: khanster/shopping-ms:kube
          name: shopping-ms
          ports:
            - containerPort: 8090
              protocol: TCP
        - image: khanster/auth-client:kube
          name: auth-client
          ports:
            - containerPort: 8090
              protocol: TCP
        - env:
            - name: MYSQL_DATABASE
              value: users
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          image: mysql:8.0
          name: mysqldb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
        - image: mongo
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim0       
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: mongodb-claim0
          persistentVolumeClaim:
            claimName: mongodb-claim0