apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shopping-ms
  name: shopping-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopping-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: shopping-ms
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/shoppingdb
          image: khanster/shopping-ms:kube
          name: shopping-ms
          ports:
            - containerPort: 8060
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/app
              name: shopping-ms-cm0
            - mountPath: /root/.m2
              name: shopping-ms-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: shopping-ms-cm0
          name: shopping-ms-cm0
        - name: shopping-ms-claim1
          persistentVolumeClaim:
            claimName: shopping-ms-claim1
