apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shopping-ms
  name: shopping-ms
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.13
  externalIP: 10.96.0.13
  externalTrafficPolicy: Local
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8060
  selector:
    io.kompose.service: shopping-ms
